name: CI - Worker

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Version Node.js'
        required: true
        default: '16'
        type: choice
        options:
          - '16'
          - '18'
          - '20'
          - '22'
      run-tests:
        description: 'Exécuter les tests ?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  ci:
    uses: nohaila1231/template-pro/.github/workflows/ci.yml@main
    with:
      node-version: ${{ github.event.inputs.node-version }}
      run-tests: ${{ github.event.inputs.run-tests == 'true' }}
